version: "3.8"
services:
  service-email:
   build: ./email-service
   ports:
     - 8094:3004
  service-clients:
   build: ./client-services
   ports:
     - 8095:3005
  service-products:
   build: ./products-services
   ports:
     - 8096:3006
